Desktop version
Mahamadou-Nouridine/My-Portfolio pull request #4
Opened 2023-03-29 17:43 UTC by Mahamadou-Nouridine

In this PR I've done these tasks:
- Desktop version of the navbar
- Desktop version of the headline section
- Desktop version of works section
- Desktop version of about me section
- Desktop version of contact form

2023-03-29 19:52 UTC, aamirkhan2478 requested changes
Hi @Mahamadou-Nouridine , 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters checked

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 19:52 UTC, aamirkhan2478 commented on about.css
> +  }
- [ ] Your design looks very nice :clap: but if you see Figma's design the cards are not the same as your cards. Kindly stick to the Figma design and fix your issue. Also when you hover any card then the overlay will disappear and the button will be shown a comparison of  your design to the Figma design check below :point_down: 

**Your Design**
![Screenshot from 2023-03-30 00-10-24](https://user-images.githubusercontent.com/45226848/228643195-ed40436b-146d-44d4-a041-1247f2de04c7.png)

**Figma design**
![Screenshot from 2023-03-29 23-58-57](https://user-images.githubusercontent.com/45226848/228643239-4a33ddd0-0f37-41b5-a2fa-91f6eed1212c.png)

- [ ] If you see all cards of Figma design you will see an overlay on all the cards except one card and that card you will style if someone is hovering over any of your cards the overlay will disappear and the button will be shown as I mentioned above :point_up: 
- [ ] Check below :point_down:  my video and forget about the design in this video you can just focus on when I hover over any of my cards the button is shown and the overlay is hidden :slightly_smiling_face: 

**[Video](https://user-images.githubusercontent.com/45226848/228644898-c8492779-4293-4033-9286-24438f55c9d7.webm)**

**_Note: You will implement these changes only for the desktop version, not for the mobile version_**

2023-03-29 19:52 UTC, aamirkhan2478 commented on style.css
> +  }
- [ ] Please stick to the Figma design your form heading is not the same as the Figma design so kindly fix it :+1: check below :point_down:  the comparison of your design and Figma design :slightly_smiling_face: 

**Your design**
![Screenshot from 2023-03-30 00-26-37](https://user-images.githubusercontent.com/45226848/228647801-622592c1-15ac-47dd-8e98-d672d055d09e.png)

**Figma design**
![Screenshot from 2023-03-30 00-26-21](https://user-images.githubusercontent.com/45226848/228647780-071a2dca-07ec-4ace-8fd7-f37372a26da0.png)

- [ ] So if you see your design the `text-align` of your `heading`  and Figma design `heading` is not the same. Also, please remove `three dots` after `something text` its not look professional so kindly fix all these changes. :+1:

2023-03-29 19:52 UTC, aamirkhan2478 commented on index.html
> +        </ul>
- [ ] As I mentioned above :point_up: please stick to the Figma design your social media icons are totally different from the Figma design. Check below :point_down: the comparison between your design and Figma design :+1: 

**Your design**
- ![Screenshot from 2023-03-30 00-40-27](https://user-images.githubusercontent.com/45226848/228650603-c3a257e6-8f55-4d8b-a217-e7c43b2b1669.png)

- ![Screenshot from 2023-03-30 00-40-38](https://user-images.githubusercontent.com/45226848/228651154-8635425a-6313-4f25-b96f-5620110a2e53.png)

**Figma design** 
- ![Screenshot from 2023-03-30 00-41-06](https://user-images.githubusercontent.com/45226848/228650630-67130d2f-6894-4bfe-8a72-13c490861e91.png)
- ![Screenshot from 2023-03-30 00-40-49](https://user-images.githubusercontent.com/45226848/228651261-e558ed12-0e57-41a2-9347-453cac9069c7.png)

- [ ] So kindly use the same social media icons as mentioned in Figma design :slightly_smiling_face:

2023-03-30 09:29 UTC, aamirkhan2478 requested changes
Hi @Mahamadou-Nouridine , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters checked

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 09:29 UTC, aamirkhan2478 commented on about.css
> +  }
- [ ] Great job so far :clap: but as I mentioned in my previous review whenever hover over any card the `overlay` will disappear and pic will be shown clearly check below :point_down: the Figma and your design comparison :slightly_smiling_face: 

**Your Design**
![Screenshot from 2023-03-30 14-15-27](https://user-images.githubusercontent.com/45226848/228791530-75427e2b-1a42-4298-908e-4f28458730f2.png)

**Figma Design**
![Screenshot from 2023-03-29 23-58-57](https://user-images.githubusercontent.com/45226848/228791424-86652267-5539-42a0-85d4-f6587dc33cf0.png)

- [ ] If you check your design the picture is not shown clearly but if you check Figma design the Picture is clear whenever someone is hovering over any card so kindly fix this issue also :+1:

2023-03-30 09:51 UTC, Lizdev-05 approved these changes
Hi @Mahamadou-Nouridine, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>
## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters checked
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 10:09 UTC, merged